// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/orderer.proto

package orderer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// resolve global log position
type ResolvePositionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	GlobalPosition int64                  `protobuf:"varint,1,opt,name=global_position,json=globalPosition,proto3" json:"global_position,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResolvePositionRequest) Reset() {
	*x = ResolvePositionRequest{}
	mi := &file_proto_orderer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvePositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvePositionRequest) ProtoMessage() {}

func (x *ResolvePositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orderer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvePositionRequest.ProtoReflect.Descriptor instead.
func (*ResolvePositionRequest) Descriptor() ([]byte, []int) {
	return file_proto_orderer_proto_rawDescGZIP(), []int{0}
}

func (x *ResolvePositionRequest) GetGlobalPosition() int64 {
	if x != nil {
		return x.GlobalPosition
	}
	return 0
}

type ResolvePositionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecordId      string                 `protobuf:"bytes,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	ShardId       string                 `protobuf:"bytes,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolvePositionResponse) Reset() {
	*x = ResolvePositionResponse{}
	mi := &file_proto_orderer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvePositionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvePositionResponse) ProtoMessage() {}

func (x *ResolvePositionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orderer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvePositionResponse.ProtoReflect.Descriptor instead.
func (*ResolvePositionResponse) Descriptor() ([]byte, []int) {
	return file_proto_orderer_proto_rawDescGZIP(), []int{1}
}

func (x *ResolvePositionResponse) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

func (x *ResolvePositionResponse) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

var File_proto_orderer_proto protoreflect.FileDescriptor

const file_proto_orderer_proto_rawDesc = "" +
	"\n" +
	"\x13proto/orderer.proto\x12\aorderer\"A\n" +
	"\x16ResolvePositionRequest\x12'\n" +
	"\x0fglobal_position\x18\x01 \x01(\x03R\x0eglobalPosition\"Q\n" +
	"\x17ResolvePositionResponse\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\tR\brecordId\x12\x19\n" +
	"\bshard_id\x18\x02 \x01(\tR\ashardId2_\n" +
	"\aOrderer\x12T\n" +
	"\x0fResolvePosition\x12\x1f.orderer.ResolvePositionRequest\x1a .orderer.ResolvePositionResponseB+Z)github.com/AbhiK57/Lazy-NCL/proto/ordererb\x06proto3"

var (
	file_proto_orderer_proto_rawDescOnce sync.Once
	file_proto_orderer_proto_rawDescData []byte
)

func file_proto_orderer_proto_rawDescGZIP() []byte {
	file_proto_orderer_proto_rawDescOnce.Do(func() {
		file_proto_orderer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_orderer_proto_rawDesc), len(file_proto_orderer_proto_rawDesc)))
	})
	return file_proto_orderer_proto_rawDescData
}

var file_proto_orderer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_orderer_proto_goTypes = []any{
	(*ResolvePositionRequest)(nil),  // 0: orderer.ResolvePositionRequest
	(*ResolvePositionResponse)(nil), // 1: orderer.ResolvePositionResponse
}
var file_proto_orderer_proto_depIdxs = []int32{
	0, // 0: orderer.Orderer.ResolvePosition:input_type -> orderer.ResolvePositionRequest
	1, // 1: orderer.Orderer.ResolvePosition:output_type -> orderer.ResolvePositionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_orderer_proto_init() }
func file_proto_orderer_proto_init() {
	if File_proto_orderer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_orderer_proto_rawDesc), len(file_proto_orderer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_orderer_proto_goTypes,
		DependencyIndexes: file_proto_orderer_proto_depIdxs,
		MessageInfos:      file_proto_orderer_proto_msgTypes,
	}.Build()
	File_proto_orderer_proto = out.File
	file_proto_orderer_proto_goTypes = nil
	file_proto_orderer_proto_depIdxs = nil
}
