// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/orderer.proto

package orderer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Orderer_ResolvePosition_FullMethodName = "/orderer.Orderer/ResolvePosition"
)

// OrdererClient is the client API for Orderer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// reads from finalized global log
type OrdererClient interface {
	// given log position returns record and shard ids
	ResolvePosition(ctx context.Context, in *ResolvePositionRequest, opts ...grpc.CallOption) (*ResolvePositionResponse, error)
}

type ordererClient struct {
	cc grpc.ClientConnInterface
}

func NewOrdererClient(cc grpc.ClientConnInterface) OrdererClient {
	return &ordererClient{cc}
}

func (c *ordererClient) ResolvePosition(ctx context.Context, in *ResolvePositionRequest, opts ...grpc.CallOption) (*ResolvePositionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolvePositionResponse)
	err := c.cc.Invoke(ctx, Orderer_ResolvePosition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrdererServer is the server API for Orderer service.
// All implementations must embed UnimplementedOrdererServer
// for forward compatibility.
//
// reads from finalized global log
type OrdererServer interface {
	// given log position returns record and shard ids
	ResolvePosition(context.Context, *ResolvePositionRequest) (*ResolvePositionResponse, error)
	mustEmbedUnimplementedOrdererServer()
}

// UnimplementedOrdererServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrdererServer struct{}

func (UnimplementedOrdererServer) ResolvePosition(context.Context, *ResolvePositionRequest) (*ResolvePositionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolvePosition not implemented")
}
func (UnimplementedOrdererServer) mustEmbedUnimplementedOrdererServer() {}
func (UnimplementedOrdererServer) testEmbeddedByValue()                 {}

// UnsafeOrdererServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrdererServer will
// result in compilation errors.
type UnsafeOrdererServer interface {
	mustEmbedUnimplementedOrdererServer()
}

func RegisterOrdererServer(s grpc.ServiceRegistrar, srv OrdererServer) {
	// If the following call pancis, it indicates UnimplementedOrdererServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Orderer_ServiceDesc, srv)
}

func _Orderer_ResolvePosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolvePositionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrdererServer).ResolvePosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orderer_ResolvePosition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrdererServer).ResolvePosition(ctx, req.(*ResolvePositionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Orderer_ServiceDesc is the grpc.ServiceDesc for Orderer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Orderer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orderer.Orderer",
	HandlerType: (*OrdererServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResolvePosition",
			Handler:    _Orderer_ResolvePosition_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/orderer.proto",
}
