// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/datashard.proto

package datashard

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PutDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecordId      string                 `protobuf:"bytes,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	DataPayload   []byte                 `protobuf:"bytes,2,opt,name=data_payload,json=dataPayload,proto3" json:"data_payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutDataRequest) Reset() {
	*x = PutDataRequest{}
	mi := &file_proto_datashard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutDataRequest) ProtoMessage() {}

func (x *PutDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datashard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutDataRequest.ProtoReflect.Descriptor instead.
func (*PutDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_datashard_proto_rawDescGZIP(), []int{0}
}

func (x *PutDataRequest) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

func (x *PutDataRequest) GetDataPayload() []byte {
	if x != nil {
		return x.DataPayload
	}
	return nil
}

// response for successful data put
type PutDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutDataResponse) Reset() {
	*x = PutDataResponse{}
	mi := &file_proto_datashard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutDataResponse) ProtoMessage() {}

func (x *PutDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datashard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutDataResponse.ProtoReflect.Descriptor instead.
func (*PutDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_datashard_proto_rawDescGZIP(), []int{1}
}

// request to receive data payload
type GetDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecordId      string                 `protobuf:"bytes,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDataRequest) Reset() {
	*x = GetDataRequest{}
	mi := &file_proto_datashard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataRequest) ProtoMessage() {}

func (x *GetDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datashard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataRequest.ProtoReflect.Descriptor instead.
func (*GetDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_datashard_proto_rawDescGZIP(), []int{2}
}

func (x *GetDataRequest) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

// response containing payload
type GetDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataPayload   []byte                 `protobuf:"bytes,1,opt,name=data_payload,json=dataPayload,proto3" json:"data_payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDataResponse) Reset() {
	*x = GetDataResponse{}
	mi := &file_proto_datashard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataResponse) ProtoMessage() {}

func (x *GetDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_datashard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataResponse.ProtoReflect.Descriptor instead.
func (*GetDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_datashard_proto_rawDescGZIP(), []int{3}
}

func (x *GetDataResponse) GetDataPayload() []byte {
	if x != nil {
		return x.DataPayload
	}
	return nil
}

var File_proto_datashard_proto protoreflect.FileDescriptor

const file_proto_datashard_proto_rawDesc = "" +
	"\n" +
	"\x15proto/datashard.proto\x12\tdatashard\"P\n" +
	"\x0ePutDataRequest\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\tR\brecordId\x12!\n" +
	"\fdata_payload\x18\x02 \x01(\fR\vdataPayload\"\x11\n" +
	"\x0fPutDataResponse\"-\n" +
	"\x0eGetDataRequest\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\tR\brecordId\"4\n" +
	"\x0fGetDataResponse\x12!\n" +
	"\fdata_payload\x18\x01 \x01(\fR\vdataPayload2\x8f\x01\n" +
	"\tDataShard\x12@\n" +
	"\aPutData\x12\x19.datashard.PutDataRequest\x1a\x1a.datashard.PutDataResponse\x12@\n" +
	"\aGetData\x12\x19.datashard.GetDataRequest\x1a\x1a.datashard.GetDataResponseB-Z+github.com/AbhiK57/Lazy-NCL/proto/datashardb\x06proto3"

var (
	file_proto_datashard_proto_rawDescOnce sync.Once
	file_proto_datashard_proto_rawDescData []byte
)

func file_proto_datashard_proto_rawDescGZIP() []byte {
	file_proto_datashard_proto_rawDescOnce.Do(func() {
		file_proto_datashard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_datashard_proto_rawDesc), len(file_proto_datashard_proto_rawDesc)))
	})
	return file_proto_datashard_proto_rawDescData
}

var file_proto_datashard_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_datashard_proto_goTypes = []any{
	(*PutDataRequest)(nil),  // 0: datashard.PutDataRequest
	(*PutDataResponse)(nil), // 1: datashard.PutDataResponse
	(*GetDataRequest)(nil),  // 2: datashard.GetDataRequest
	(*GetDataResponse)(nil), // 3: datashard.GetDataResponse
}
var file_proto_datashard_proto_depIdxs = []int32{
	0, // 0: datashard.DataShard.PutData:input_type -> datashard.PutDataRequest
	2, // 1: datashard.DataShard.GetData:input_type -> datashard.GetDataRequest
	1, // 2: datashard.DataShard.PutData:output_type -> datashard.PutDataResponse
	3, // 3: datashard.DataShard.GetData:output_type -> datashard.GetDataResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_datashard_proto_init() }
func file_proto_datashard_proto_init() {
	if File_proto_datashard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_datashard_proto_rawDesc), len(file_proto_datashard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_datashard_proto_goTypes,
		DependencyIndexes: file_proto_datashard_proto_depIdxs,
		MessageInfos:      file_proto_datashard_proto_msgTypes,
	}.Build()
	File_proto_datashard_proto = out.File
	file_proto_datashard_proto_goTypes = nil
	file_proto_datashard_proto_depIdxs = nil
}
