// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/datashard.proto

package datashard

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataShard_PutData_FullMethodName = "/datashard.DataShard/PutData"
	DataShard_GetData_FullMethodName = "/datashard.DataShard/GetData"
)

// DataShardClient is the client API for DataShard service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataShardClient interface {
	// Stores a data payload, indexed by its record_id.
	PutData(ctx context.Context, in *PutDataRequest, opts ...grpc.CallOption) (*PutDataResponse, error)
	// Retrieves a data payload by its record_id.
	GetData(ctx context.Context, in *GetDataRequest, opts ...grpc.CallOption) (*GetDataResponse, error)
}

type dataShardClient struct {
	cc grpc.ClientConnInterface
}

func NewDataShardClient(cc grpc.ClientConnInterface) DataShardClient {
	return &dataShardClient{cc}
}

func (c *dataShardClient) PutData(ctx context.Context, in *PutDataRequest, opts ...grpc.CallOption) (*PutDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutDataResponse)
	err := c.cc.Invoke(ctx, DataShard_PutData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataShardClient) GetData(ctx context.Context, in *GetDataRequest, opts ...grpc.CallOption) (*GetDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDataResponse)
	err := c.cc.Invoke(ctx, DataShard_GetData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataShardServer is the server API for DataShard service.
// All implementations must embed UnimplementedDataShardServer
// for forward compatibility.
type DataShardServer interface {
	// Stores a data payload, indexed by its record_id.
	PutData(context.Context, *PutDataRequest) (*PutDataResponse, error)
	// Retrieves a data payload by its record_id.
	GetData(context.Context, *GetDataRequest) (*GetDataResponse, error)
	mustEmbedUnimplementedDataShardServer()
}

// UnimplementedDataShardServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataShardServer struct{}

func (UnimplementedDataShardServer) PutData(context.Context, *PutDataRequest) (*PutDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutData not implemented")
}
func (UnimplementedDataShardServer) GetData(context.Context, *GetDataRequest) (*GetDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetData not implemented")
}
func (UnimplementedDataShardServer) mustEmbedUnimplementedDataShardServer() {}
func (UnimplementedDataShardServer) testEmbeddedByValue()                   {}

// UnsafeDataShardServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataShardServer will
// result in compilation errors.
type UnsafeDataShardServer interface {
	mustEmbedUnimplementedDataShardServer()
}

func RegisterDataShardServer(s grpc.ServiceRegistrar, srv DataShardServer) {
	// If the following call pancis, it indicates UnimplementedDataShardServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataShard_ServiceDesc, srv)
}

func _DataShard_PutData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataShardServer).PutData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataShard_PutData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataShardServer).PutData(ctx, req.(*PutDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataShard_GetData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataShardServer).GetData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataShard_GetData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataShardServer).GetData(ctx, req.(*GetDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataShard_ServiceDesc is the grpc.ServiceDesc for DataShard service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataShard_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "datashard.DataShard",
	HandlerType: (*DataShardServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutData",
			Handler:    _DataShard_PutData_Handler,
		},
		{
			MethodName: "GetData",
			Handler:    _DataShard_GetData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/datashard.proto",
}
