// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/ncl.proto

package ncl

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// metdata for single record
type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecordId      string                 `protobuf:"bytes,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"` //Globally unique ID for record
	ShardId       string                 `protobuf:"bytes,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`    //id of datashard for payload
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_proto_ncl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ncl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_proto_ncl_proto_rawDescGZIP(), []int{0}
}

func (x *Metadata) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

func (x *Metadata) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

// request to append metadata to an NCL peer
type AppendMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Metadata              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendMetadataRequest) Reset() {
	*x = AppendMetadataRequest{}
	mi := &file_proto_ncl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendMetadataRequest) ProtoMessage() {}

func (x *AppendMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ncl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendMetadataRequest.ProtoReflect.Descriptor instead.
func (*AppendMetadataRequest) Descriptor() ([]byte, []int) {
	return file_proto_ncl_proto_rawDescGZIP(), []int{1}
}

func (x *AppendMetadataRequest) GetMeta() *Metadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

// response to successful append
type AppendMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendMetadataResponse) Reset() {
	*x = AppendMetadataResponse{}
	mi := &file_proto_ncl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendMetadataResponse) ProtoMessage() {}

func (x *AppendMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ncl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendMetadataResponse.ProtoReflect.Descriptor instead.
func (*AppendMetadataResponse) Descriptor() ([]byte, []int) {
	return file_proto_ncl_proto_rawDescGZIP(), []int{2}
}

// request to read from specific offset
type ReadMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int64                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadMetadataRequest) Reset() {
	*x = ReadMetadataRequest{}
	mi := &file_proto_ncl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMetadataRequest) ProtoMessage() {}

func (x *ReadMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ncl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMetadataRequest.ProtoReflect.Descriptor instead.
func (*ReadMetadataRequest) Descriptor() ([]byte, []int) {
	return file_proto_ncl_proto_rawDescGZIP(), []int{3}
}

func (x *ReadMetadataRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

var File_proto_ncl_proto protoreflect.FileDescriptor

const file_proto_ncl_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/ncl.proto\x12\x03ncl\"B\n" +
	"\bMetadata\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\tR\brecordId\x12\x19\n" +
	"\bshard_id\x18\x02 \x01(\tR\ashardId\":\n" +
	"\x15AppendMetadataRequest\x12!\n" +
	"\x04meta\x18\x01 \x01(\v2\r.ncl.MetadataR\x04meta\"\x18\n" +
	"\x16AppendMetadataResponse\"-\n" +
	"\x13ReadMetadataRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset2\x8f\x01\n" +
	"\aNCLPeer\x12I\n" +
	"\x0eAppendMetadata\x12\x1a.ncl.AppendMetadataRequest\x1a\x1b.ncl.AppendMetadataResponse\x129\n" +
	"\fReadMetadata\x12\x18.ncl.ReadMetadataRequest\x1a\r.ncl.Metadata0\x01B'Z%github.com/AbhiK57/Lazy-NCL/proto/nclb\x06proto3"

var (
	file_proto_ncl_proto_rawDescOnce sync.Once
	file_proto_ncl_proto_rawDescData []byte
)

func file_proto_ncl_proto_rawDescGZIP() []byte {
	file_proto_ncl_proto_rawDescOnce.Do(func() {
		file_proto_ncl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ncl_proto_rawDesc), len(file_proto_ncl_proto_rawDesc)))
	})
	return file_proto_ncl_proto_rawDescData
}

var file_proto_ncl_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_ncl_proto_goTypes = []any{
	(*Metadata)(nil),               // 0: ncl.Metadata
	(*AppendMetadataRequest)(nil),  // 1: ncl.AppendMetadataRequest
	(*AppendMetadataResponse)(nil), // 2: ncl.AppendMetadataResponse
	(*ReadMetadataRequest)(nil),    // 3: ncl.ReadMetadataRequest
}
var file_proto_ncl_proto_depIdxs = []int32{
	0, // 0: ncl.AppendMetadataRequest.meta:type_name -> ncl.Metadata
	1, // 1: ncl.NCLPeer.AppendMetadata:input_type -> ncl.AppendMetadataRequest
	3, // 2: ncl.NCLPeer.ReadMetadata:input_type -> ncl.ReadMetadataRequest
	2, // 3: ncl.NCLPeer.AppendMetadata:output_type -> ncl.AppendMetadataResponse
	0, // 4: ncl.NCLPeer.ReadMetadata:output_type -> ncl.Metadata
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_ncl_proto_init() }
func file_proto_ncl_proto_init() {
	if File_proto_ncl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ncl_proto_rawDesc), len(file_proto_ncl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ncl_proto_goTypes,
		DependencyIndexes: file_proto_ncl_proto_depIdxs,
		MessageInfos:      file_proto_ncl_proto_msgTypes,
	}.Build()
	File_proto_ncl_proto = out.File
	file_proto_ncl_proto_goTypes = nil
	file_proto_ncl_proto_depIdxs = nil
}
